[tool.poetry]
name = "poe-currency-flip-planner"
version = "0.3.2"
description = ""
authors = ["Maximilian stock <mxmlnstock@googlemail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.6.2"
asyncio = "^3.4.3"
attrs = "^20.2.0"
beautifulsoup4 = "^4.9.1"
requests = "^2.24.0"
marshmallow = "^3.7.1"
asyncio_throttle = "^1.0.1"
jsonpickle = "^1.4.1"
deserialize = "^1.8.0"

[tool.poetry.dev-dependencies]
mypy = "^0.782"
pytest-cov = "^2.10.0"
pytest = "^6.0.2"
flake8 = "^3.8.3"
autopep8 = "^1.5.4"
matplotlib = "^3.3.2"
notebook = "^6.1.4"
numpy = "^1.19.2"
pandas = "^1.1.2"
scipy = "^1.5.2"
yapf = "^0.30.0"
rope = "^0.17.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
